#!/usr/bin/env python3
"""Print a Perforce checkout plan for synchronizing one tree into another.

Example:
    python scripts/plan_p4_sync.py /path/to/dist /path/to/release > p4_plan.csh

The script does not invoke Perforce or copy files. Copy changed files after
opening them for edit; copy source-only files before running their add command.
"""

from __future__ import annotations

import argparse
import filecmp
import fnmatch
import re
import shlex
from collections.abc import Iterable
from pathlib import Path

VALID_FILETYPE = re.compile(r"^[A-Za-z0-9_.+-]+$")


def _files_under(root: Path, includes: tuple[str, ...]) -> set[Path]:
    """Return selected regular-file paths relative to ``root``."""

    paths = (path.relative_to(root) for path in root.rglob("*") if path.is_file())
    if not includes:
        return set(paths)
    return {path for path in paths if any(fnmatch.fnmatchcase(path.as_posix(), pattern) for pattern in includes)}


def _quoted(path: Path) -> str:
    return shlex.quote(str(path))


def _write_section(heading: str, paths: Iterable[Path], command: str | None) -> None:
    values = tuple(paths)
    if not values:
        return
    print(f"# {heading}")
    for path in values:
        if command is None:
            print(f"# {path.as_posix()}")
        else:
            print(f"{command} {_quoted(path)}")
    print()


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Print P4 edit/add commands for a source-to-release tree sync.")
    parser.add_argument("source", type=Path, help="New distribution or release source tree")
    parser.add_argument("target", type=Path, help="Existing Perforce-controlled release tree")
    parser.add_argument(
        "--include",
        action="append",
        default=[],
        metavar="GLOB",
        help="Include only relative paths matching GLOB; repeat to select multiple groups",
    )
    parser.add_argument(
        "--filetype",
        default="text+x",
        help="Perforce filetype for edit/add commands (default: text+x; use text for JSON-only plans)",
    )
    args = parser.parse_args()
    args.source = args.source.resolve()
    args.target = args.target.resolve()
    if not args.source.is_dir():
        parser.error(f"source is not a directory: {args.source}")
    if not args.target.is_dir():
        parser.error(f"target is not a directory: {args.target}")
    if args.source == args.target:
        parser.error("source and target must be different directories")
    if not VALID_FILETYPE.fullmatch(args.filetype):
        parser.error(f"invalid Perforce filetype: {args.filetype}")
    return args


def main() -> None:
    args = _parse_args()
    includes = tuple(args.include)
    source_paths = _files_under(args.source, includes)
    target_paths = _files_under(args.target, includes)
    common_paths = source_paths & target_paths
    edits = tuple(
        args.target / path
        for path in sorted(common_paths)
        if not filecmp.cmp(args.source / path, args.target / path, shallow=False)
    )
    adds = tuple(args.target / path for path in sorted(source_paths - target_paths))

    print("#!/usr/intel/bin/tcsh -f")
    print("# Generated by scripts/plan_p4_sync.py; this file does not run P4 or copy files.")
    print(f"# Source: {_quoted(args.source)}")
    print(f"# Target: {_quoted(args.target)}")
    print("# Open edits before copying changed files; copy source-only files before running p4 add.")
    print()
    _write_section("Changed files: open, then copy from source", edits, f"p4 edit -t {args.filetype}")
    _write_section("Source-only files: copy from source, then add", adds, f"p4 add -t {args.filetype}")
    _write_section(
        "Target-only files: review separately; no delete command is emitted", sorted(target_paths - source_paths), None
    )
    if not edits and not adds and not target_paths - source_paths:
        print("# No selected differences found.")


if __name__ == "__main__":
    main()
