"""
Synthetic large-domain generator for Chopper parser performance tests.

Resolves: B-13 (PRE_CODING_REVIEW.md)
Usage:    Sprint 1 acceptance — "parser < 2s on domain with 60+ Tcl files"

This script generates a synthetic domain with:
  - Configurable number of Tcl files (default: 60)
  - Configurable number of procs per file (default: 5)
  - Realistic namespace nesting (2 levels deep)
  - Realistic proc calls (each proc calls 1–3 others)
  - A mix of file-level code (set statements, comments) around the procs

The generated domain is deterministic: the same seed produces the same output.
"""

from __future__ import annotations

import argparse
import random
from pathlib import Path

# ---------------------------------------------------------------------------
# Tcl template fragments
# ---------------------------------------------------------------------------

_FILE_HEADER = """\
# Auto-generated synthetic Tcl file for Chopper performance testing.
# File: {filename}
# Generated by tests/fixtures/gen_large_domain.py

package require Tcl 8.6

set {varname}_initialized 1
"""

_NAMESPACE_OPEN = "namespace eval {ns} {{\n"
_NAMESPACE_CLOSE = "}\n"

_PROC_TEMPLATE = """\
# Proc documentation for {procname}
# Argument: args
proc {procname} {{args}} {{
    set result 0
{calls}    return $result
}}
"""

_CALL_LINE = "    {callee} arg1\n"


# ---------------------------------------------------------------------------
# Generator
# ---------------------------------------------------------------------------


def _make_ident(prefix: str, idx: int) -> str:
    return f"{prefix}_{idx:03d}"


def generate_large_domain(
    output_dir: Path,
    num_files: int = 60,
    procs_per_file: int = 5,
    seed: int = 42,
) -> list[Path]:
    """Generate a synthetic Chopper domain under *output_dir*.

    Returns the list of generated .tcl file paths.

    :param output_dir: Directory to write generated files into.
    :param num_files:  Number of .tcl files to create.
    :param procs_per_file: Number of proc definitions per file.
    :param seed: RNG seed for deterministic generation.
    :returns: Sorted list of generated .tcl Paths.
    """
    rng = random.Random(seed)
    output_dir.mkdir(parents=True, exist_ok=True)

    # Build a global list of all (namespace, procname) pairs so procs can call
    # each other realistically.
    all_procs: list[tuple[str, str]] = []
    for file_idx in range(num_files):
        ns = _make_ident("ns", file_idx % 10)  # 10 namespaces across domain
        for proc_idx in range(procs_per_file):
            all_procs.append((ns, _make_ident(f"proc_{file_idx}", proc_idx)))

    generated: list[Path] = []

    for file_idx in range(num_files):
        ns = _make_ident("ns", file_idx % 10)
        filename = f"file_{file_idx:03d}_procs.tcl"
        varname = f"file{file_idx:03d}"

        lines: list[str] = [_FILE_HEADER.format(filename=filename, varname=varname)]
        lines.append(_NAMESPACE_OPEN.format(ns=ns))

        for proc_idx in range(procs_per_file):
            procname = _make_ident(f"proc_{file_idx}", proc_idx)
            num_calls = rng.randint(1, 3)
            callees = rng.sample(all_procs, min(num_calls, len(all_procs)))
            call_lines = "".join(
                _CALL_LINE.format(callee=f"{callee_ns}::{callee_name}")
                for callee_ns, callee_name in callees
                if not (callee_ns == ns and callee_name == procname)  # no self-calls
            )
            lines.append(_PROC_TEMPLATE.format(procname=procname, calls=call_lines))

        lines.append(_NAMESPACE_CLOSE)

        tcl_path = output_dir / filename
        tcl_path.write_text("".join(lines), encoding="utf-8")
        generated.append(tcl_path)

    return sorted(generated)


# ---------------------------------------------------------------------------
# pytest fixture (importable by conftest.py)
# ---------------------------------------------------------------------------


def pytest_large_domain_fixture(tmp_path_factory):
    """Session-scoped pytest fixture that creates a 60-file synthetic domain.

    Usage in conftest.py::

        import pytest
        from tests.fixtures.gen_large_domain import pytest_large_domain_fixture

        @pytest.fixture(scope="session")
        def large_domain_60_files(tmp_path_factory):
            return pytest_large_domain_fixture(tmp_path_factory)

    The fixture returns the Path to the generated domain directory.
    """
    domain_dir = tmp_path_factory.mktemp("large_domain_60_files", numbered=False)
    generate_large_domain(domain_dir, num_files=60, procs_per_file=5)
    return domain_dir


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate a synthetic Chopper domain for performance testing.")
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("tests/fixtures/domains/large_domain"),
        help="Output directory for generated domain (default: tests/fixtures/domains/large_domain)",
    )
    parser.add_argument("--num-files", type=int, default=60, help="Number of Tcl files to generate (default: 60)")
    parser.add_argument("--procs-per-file", type=int, default=5, help="Number of procs per file (default: 5)")
    parser.add_argument("--seed", type=int, default=42, help="RNG seed for deterministic output (default: 42)")
    args = parser.parse_args()

    files = generate_large_domain(
        args.output,
        num_files=args.num_files,
        procs_per_file=args.procs_per_file,
        seed=args.seed,
    )
    print(f"Generated {len(files)} files in {args.output}")
    print(f"Total procs: {args.num_files * args.procs_per_file}")


if __name__ == "__main__":
    main()
